### ISSUE TITLE
Trying to compile the Swift version but having problems with Pods

### ISSUE THREAD

**Issue by eisnerguy1** [CD1212/Doughnut#4]
Really enjoying the simple to use Electron version (iTunes way too bloated for me right now) and was going to try the Swift version.  Had some few problems.  When I run "pod install" this happens:

```
Analyzing dependencies
Pre-downloading: `FeedKit` from `https://github.com/CD1212/FeedKit.git`
[!] Unable to find a specification for `GRDB.swift`

[!] Automatically assigning platform osx with version 10.12 on target Doughnut because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

I've updated CocoaPods and everything.  When I tried building the app in Xcode, I got these 3 errors:
```
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```
Any help would be great.  Thanks!

**Comment by CD1212** [comment]
I'm really pleased to hear you have been finding this project useful! I abandoned the Electron version a while back and the swift version should have most of the same features, if not a few more. I haven't merged it into master yet because it doesn't yet automatically refresh each podcast feed, you still need to right click each one and choose reload.

I just tried a fresh clone and `pod install` worked correctly. `GRDB.swift` should be a perfectly valid Cocoapod: https://cocoapods.org/pods/GRDB.swift

What version of Xcode / Swift are you using? It looks as though GRDB requires Swift 4.

**Comment by CD1212** [comment]
I have just merged the swift branch into master and have included the Pods directory in the git repository. There shouldn't be a need to run `pod install` anymore, when you open `Doughnut.xcworkspace` it should just build.

Hope this helps solve your problem.
